import { Ionicons } from '@expo/vector-icons';
import { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { EmptyState, ErrorState, LoadingState, ScreenHeader, TransactionRow } from '@/components';
import { TransactionForm } from '@/forms';
import { useStore } from '@/store';
import { colors } from '@/theme';
import { Transaction, TransactionType } from '@/types';

export default function History() {
  const { top } = useSafeAreaInsets(); const store = useStore();
  const [search, setSearch] = useState(''); const [type, setType] = useState<'all' | TransactionType>('all'); const [category, setCategory] = useState('All'); const [walletId, setWalletId] = useState('all'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [editing, setEditing] = useState<Transaction | null>(null); const [formOpen, setFormOpen] = useState(false);
  const categories = ['All', ...Array.from(new Set(store.transactions.map((item) => item.category)))];
  const filtered = useMemo(() => store.transactions.filter((item) => (!search || item.description.toLowerCase().includes(search.toLowerCase())) && (type === 'all' || item.type === type) && (category === 'All' || item.category === category) && (walletId === 'all' || item.walletId === walletId) && (!from || item.transactionDate >= from) && (!to || item.transactionDate <= to)), [store.transactions, search, type, category, walletId, from, to]);
  function confirmDelete(item: Transaction) { Alert.alert('Delete transaction?', 'This will immediately update the linked wallet balance and reports.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => store.removeTransaction(item.id).catch(() => Alert.alert('Could not delete', 'Check your connection and try again.')) }]); }
  function openEdit(item: Transaction) { setEditing(item); setFormOpen(true); }
  return <ScrollView style={s.page} contentContainerStyle={{ paddingTop: top + 16, paddingHorizontal: 18, paddingBottom: 30 }} keyboardShouldPersistTaps="handled"><ScreenHeader eyebrow="Search and manage your records" title="History" action={<Pressable style={s.add} onPress={() => { setEditing(null); setFormOpen(true); }}><Ionicons name="add" size={22} color="white" /></Pressable>} />
    <View style={s.search}><Ionicons name="search" size={19} color={colors.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Search descriptions" placeholderTextColor="#9AA39E" style={s.searchInput} /></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{(['all', 'expense', 'income'] as const).map((value) => <Pressable key={value} onPress={() => setType(value)} style={[s.chip, type === value && s.chipOn]}><Text style={[s.chipText, type === value && s.chipTextOn]}>{value === 'all' ? 'All types' : value[0].toUpperCase() + value.slice(1)}</Text></Pressable>)}{categories.map((value) => <Pressable key={value} onPress={() => setCategory(value)} style={[s.chip, category === value && s.chipOn]}><Text style={[s.chipText, category === value && s.chipTextOn]}>{value}</Text></Pressable>)}</ScrollView>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}><Pressable onPress={() => setWalletId('all')} style={[s.chip, walletId === 'all' && s.chipOn]}><Text style={[s.chipText, walletId === 'all' && s.chipTextOn]}>All wallets</Text></Pressable>{store.wallets.map((wallet) => <Pressable key={wallet.id} onPress={() => setWalletId(wallet.id)} style={[s.chip, walletId === wallet.id && s.chipOn]}><Text style={[s.chipText, walletId === wallet.id && s.chipTextOn]}>{wallet.name}</Text></Pressable>)}</ScrollView>
    <View style={s.dates}><View style={{ flex: 1 }}><Text style={s.label}>FROM</Text><TextInput value={from} onChangeText={setFrom} placeholder="YYYY-MM-DD" style={s.dateInput} /></View><View style={{ flex: 1 }}><Text style={s.label}>TO</Text><TextInput value={to} onChangeText={setTo} placeholder="YYYY-MM-DD" style={s.dateInput} /></View></View>
    <Text style={s.count}>{filtered.length} {filtered.length === 1 ? 'transaction' : 'transactions'}</Text>{store.error ? <ErrorState message={store.error} /> : !store.loaded ? <LoadingState /> : filtered.length ? <View style={s.list}>{filtered.map((item) => <Pressable key={item.id} onLongPress={() => confirmDelete(item)} onPress={() => openEdit(item)}><TransactionRow item={item} wallet={store.wallets.find((wallet) => wallet.id === item.walletId)} /><View style={s.actions}><Text style={s.actionHint}>Tap to edit · Hold to delete</Text></View></Pressable>)}</View> : <EmptyState icon="search-outline" title="No matching transactions" body="Adjust your search or filters, or add a new record." />}
    <TransactionForm visible={formOpen} initial={editing} wallets={store.wallets} onClose={() => setFormOpen(false)} onSave={(value) => editing ? store.updateTransaction(editing.id, value) : store.addTransaction(value)} />
  </ScrollView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream }, add: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' }, search: { height: 50, flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: 'white', borderRadius: 15, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.line }, searchInput: { flex: 1, color: colors.ink }, filters: { gap: 7, paddingVertical: 10 }, chip: { height: 36, justifyContent: 'center', paddingHorizontal: 12, borderRadius: 12, backgroundColor: 'white', borderWidth: 1, borderColor: colors.line }, chipOn: { backgroundColor: colors.green, borderColor: colors.green }, chipText: { color: colors.ink, fontWeight: '700', fontSize: 11 }, chipTextOn: { color: 'white' }, dates: { flexDirection: 'row', gap: 10 }, label: { fontSize: 9, fontWeight: '800', color: colors.muted, marginBottom: 5 }, dateInput: { height: 43, backgroundColor: 'white', borderRadius: 12, paddingHorizontal: 11, color: colors.ink, borderWidth: 1, borderColor: colors.line, fontSize: 12 }, count: { color: colors.muted, fontWeight: '700', fontSize: 11, marginTop: 16, marginBottom: 8 }, list: { backgroundColor: 'white', borderRadius: 19, paddingHorizontal: 15 }, actions: { alignItems: 'flex-end', marginTop: -8, paddingBottom: 4 }, actionHint: { color: '#A1AAA5', fontSize: 8 } });
