import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ErrorState, LoadingState, ScreenHeader } from '@/components';
import { currentMonth, fromCents, pesos, toCents } from '@/money';
import { useStore } from '@/store';
import { colors } from '@/theme';
import { EXPENSE_CATEGORIES, ExpenseCategory } from '@/types';

export default function Budgets() {
  const { top } = useSafeAreaInsets(); const store = useStore(); const month = currentMonth(); const current = store.budgets.find((item) => item.month === month);
  const [overall, setOverall] = useState(''); const [categories, setCategories] = useState<Partial<Record<ExpenseCategory, string>>>({}); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { if (store.loaded) { setOverall(current ? fromCents(current.overallCents) : ''); setCategories(Object.fromEntries(EXPENSE_CATEGORIES.map((name) => [name, current?.categories[name] ? fromCents(current.categories[name]!) : '']))); } }, [store.loaded, current?.updatedAt]);
  const expenses = store.transactions.filter((item) => item.type === 'expense' && item.transactionDate.startsWith(month)); const totalSpent = expenses.reduce((sum, item) => sum + item.amountCents, 0); const overallCents = toCents(overall);
  async function save() { if (overallCents <= 0) { setMessage('Enter a positive overall monthly budget.'); return; } setSaving(true); setMessage(''); try { const values: Partial<Record<ExpenseCategory, number>> = {}; EXPENSE_CATEGORIES.forEach((name) => { const value = toCents(categories[name] || ''); if (value > 0) values[name] = value; }); await store.saveBudget({ month, overallCents, categories: values }); setMessage('Budget saved.'); } catch { setMessage('Could not save your budget. Check your connection.'); } finally { setSaving(false); } }
  return <KeyboardAvoidingView style={s.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={{ paddingTop: top + 16, paddingHorizontal: 18, paddingBottom: 34 }} keyboardShouldPersistTaps="handled"><ScreenHeader eyebrow={`Plan for ${new Date(`${month}-02`).toLocaleDateString('en-PH', { month: 'long', year: 'numeric' })}`} title="Budgets" />{store.error ? <ErrorState message={store.error} /> : !store.loaded ? <LoadingState /> : <><View style={[s.summary, totalSpent > overallCents && overallCents > 0 && s.summaryOver]}><Text style={s.summaryLabel}>MONTHLY SPENDING</Text><View style={s.summaryRow}><Text style={s.spent}>{pesos(totalSpent)}</Text><Text style={[s.remaining, totalSpent > overallCents && overallCents > 0 && { color: colors.red }]}>{overallCents ? `${pesos(Math.abs(overallCents - totalSpent))} ${totalSpent > overallCents ? 'over' : 'left'}` : 'Set a budget'}</Text></View><View style={s.track}><View style={[s.fill, { width: `${overallCents ? Math.min(100, totalSpent / overallCents * 100) : 0}%`, backgroundColor: totalSpent > overallCents ? colors.red : colors.green }]} /></View></View>
    <Text style={s.label}>OVERALL MONTHLY EXPENSE BUDGET</Text><View style={s.moneyInput}><Text style={s.peso}>₱</Text><TextInput value={overall} onChangeText={setOverall} keyboardType="decimal-pad" placeholder="0.00" style={s.input} /></View><Text style={s.note}>Category budgets below are breakdowns of this overall budget; they are not added on top.</Text>
    <Text style={s.heading}>Category breakdowns</Text>{EXPENSE_CATEGORIES.map((name) => { const spent = expenses.filter((item) => item.category === name).reduce((sum, item) => sum + item.amountCents, 0); const limit = toCents(categories[name] || ''); const exceeded = limit > 0 && spent > limit; return <View key={name} style={s.category}><View style={s.categoryTop}><View><Text style={s.categoryName}>{name}</Text><Text style={[s.categorySpent, exceeded && { color: colors.red }]}>{pesos(spent)} spent{exceeded ? ' · exceeded' : ''}</Text></View><View style={s.smallMoney}><Text style={s.smallPeso}>₱</Text><TextInput value={categories[name] || ''} onChangeText={(value) => setCategories((old) => ({ ...old, [name]: value }))} keyboardType="decimal-pad" placeholder="Optional" style={s.smallInput} /></View></View>{limit > 0 && <View style={s.track}><View style={[s.fill, { width: `${Math.min(100, spent / limit * 100)}%`, backgroundColor: exceeded ? colors.red : colors.green }]} /></View>}</View>; })}
    {!!message && <Text style={[s.message, message.includes('saved') && { color: colors.green }]}>{message}</Text>}<Pressable disabled={saving} onPress={save} style={[s.save, saving && { opacity: .5 }]}><Ionicons name="checkmark-circle-outline" size={21} color="white" /><Text style={s.saveText}>{saving ? 'Saving…' : 'Save monthly budget'}</Text></Pressable></>}
  </ScrollView></KeyboardAvoidingView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream }, summary: { backgroundColor: colors.mint, borderRadius: 21, padding: 18 }, summaryOver: { backgroundColor: '#FFF0EE' }, summaryLabel: { color: colors.green, fontSize: 9, fontWeight: '800', letterSpacing: 1 }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginVertical: 9 }, spent: { fontSize: 27, color: colors.ink, fontWeight: '800' }, remaining: { color: colors.green, fontWeight: '700', fontSize: 11 }, track: { height: 7, borderRadius: 4, backgroundColor: '#DDE2DE', overflow: 'hidden', marginTop: 7 }, fill: { height: 7, borderRadius: 4 }, label: { color: colors.muted, fontWeight: '800', fontSize: 10, letterSpacing: 1, marginTop: 23, marginBottom: 5 }, moneyInput: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'white', borderRadius: 15, paddingHorizontal: 14 }, peso: { fontSize: 23, color: colors.muted, fontWeight: '700' }, input: { flex: 1, height: 54, fontSize: 22, color: colors.ink, fontWeight: '800' }, note: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 7 }, heading: { fontSize: 18, fontWeight: '800', color: colors.ink, marginTop: 26, marginBottom: 9 }, category: { backgroundColor: 'white', padding: 14, borderRadius: 16, marginBottom: 8 }, categoryTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, categoryName: { color: colors.ink, fontWeight: '800', fontSize: 13 }, categorySpent: { color: colors.muted, fontSize: 10, marginTop: 3 }, smallMoney: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.cream, borderRadius: 10, paddingHorizontal: 8 }, smallPeso: { color: colors.muted, fontWeight: '700' }, smallInput: { width: 80, height: 38, color: colors.ink, fontWeight: '700', fontSize: 12 }, message: { color: colors.red, fontSize: 12, textAlign: 'center', marginTop: 12 }, save: { height: 55, borderRadius: 17, backgroundColor: colors.green, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 18 }, saveText: { color: 'white', fontWeight: '800' } });
