import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { signOut } from 'firebase/auth';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { EmptyState, ErrorState, LoadingState, ScreenHeader, TransactionRow } from '@/components';
import { auth } from '@/firebase';
import { TransactionForm, WalletForm } from '@/forms';
import { currentMonth, pesos, previousMonth } from '@/money';
import { useStore } from '@/store';
import { colors } from '@/theme';

export default function Dashboard() {
  const { top } = useSafeAreaInsets(); const store = useStore();
  const [transactionOpen, setTransactionOpen] = useState(false); const [walletOpen, setWalletOpen] = useState(false);
  const month = currentMonth(); const lastMonth = previousMonth(month);
  const monthly = store.transactions.filter((item) => item.transactionDate.startsWith(month));
  const income = monthly.filter((item) => item.type === 'income').reduce((sum, item) => sum + item.amountCents, 0);
  const expenses = monthly.filter((item) => item.type === 'expense').reduce((sum, item) => sum + item.amountCents, 0);
  const balance = store.wallets.reduce((sum, wallet) => sum + store.walletBalance(wallet.id), 0);
  const budget = store.budgets.find((item) => item.month === month); const remaining = (budget?.overallCents || 0) - expenses;
  const categoryTotals = useMemo(() => monthly.filter((item) => item.type === 'expense').reduce<Record<string, number>>((all, item) => ({ ...all, [item.category]: (all[item.category] || 0) + item.amountCents }), {}), [store.transactions, month]);
  const categoryEntries = Object.entries(categoryTotals).sort((a, b) => b[1] - a[1]);
  const lastExpenses = store.transactions.filter((item) => item.type === 'expense' && item.transactionDate.startsWith(lastMonth)).reduce((sum, item) => sum + item.amountCents, 0);
  let comparison = 'There is not enough prior-month data for a comparison.';
  if (lastExpenses > 0) { const delta = Math.round((expenses - lastExpenses) / lastExpenses * 100); comparison = `You spent ${Math.abs(delta)}% ${delta > 0 ? 'more' : delta < 0 ? 'less' : 'the same'} than last month.`; }
  return <ScrollView style={s.page} contentContainerStyle={{ paddingTop: top + 16, paddingHorizontal: 18, paddingBottom: 30 }} showsVerticalScrollIndicator={false}><ScreenHeader eyebrow={new Date().toLocaleDateString('en-PH', { timeZone: 'Asia/Manila', weekday: 'long', month: 'long', day: 'numeric' })} title="Your finances" action={<Pressable onPress={() => signOut(auth)} style={s.iconButton}><Ionicons name="log-out-outline" size={21} color={colors.green} /></Pressable>} />
    {store.error && <ErrorState message={store.error} />}{!store.loaded ? <LoadingState /> : <><LinearGradient colors={[colors.green, '#286548']} style={s.hero}><Text style={s.heroLabel}>TOTAL WALLET BALANCE</Text><Text style={s.heroAmount}>{pesos(balance)}</Text><View style={s.heroStats}><View><Text style={s.heroMiniLabel}>INCOME</Text><Text style={s.income}>+{pesos(income)}</Text></View><View><Text style={s.heroMiniLabel}>EXPENSES</Text><Text style={s.expense}>−{pesos(expenses)}</Text></View></View></LinearGradient>
    <Pressable onPress={() => store.wallets.length ? setTransactionOpen(true) : setWalletOpen(true)} style={s.add}><Ionicons name="add-circle" size={22} color="white" /><Text style={s.addText}>{store.wallets.length ? 'Add transaction' : 'Create your first wallet'}</Text></Pressable>
    <View style={s.grid}><View style={s.metric}><Text style={s.metricLabel}>MONTHLY BUDGET</Text><Text style={[s.metricValue, remaining < 0 && { color: colors.red }]}>{budget ? pesos(remaining) : 'Not set'}</Text><Text style={s.metricSub}>{budget ? (remaining < 0 ? 'over budget' : 'remaining') : 'Set one in Budgets'}</Text></View><View style={s.metric}><Text style={s.metricLabel}>TOP CATEGORY</Text><Text style={s.metricValue}>{categoryEntries[0]?.[0] || '—'}</Text><Text style={s.metricSub}>{categoryEntries[0] ? pesos(categoryEntries[0][1]) : 'No expenses yet'}</Text></View></View>
    <Text style={s.heading}>Recent transactions</Text>{store.transactions.length ? <View style={s.card}>{store.transactions.slice(0, 5).map((item) => <TransactionRow key={item.id} item={item} wallet={store.wallets.find((wallet) => wallet.id === item.walletId)} />)}</View> : <EmptyState icon="receipt-outline" title="No transactions yet" body="Add income or an expense to start tracking." />}
    <Text style={s.heading}>Spending breakdown</Text><View style={s.card}>{categoryEntries.length ? categoryEntries.slice(0, 5).map(([name, value]) => <View key={name} style={s.breakdown}><View style={s.breakdownLabel}><Text style={s.breakdownName}>{name}</Text><Text style={s.breakdownValue}>{pesos(value)}</Text></View><View style={s.track}><View style={[s.fill, { width: `${expenses ? value / expenses * 100 : 0}%` }]} /></View></View>) : <Text style={s.noData}>No expense data for this month.</Text>}</View>
    <Text style={s.heading}>Spending insights</Text><View style={s.insight}><Ionicons name="sparkles" size={20} color={colors.green} /><View style={{ flex: 1 }}><Text style={s.insightTitle}>{categoryEntries[0] ? `${categoryEntries[0][0]} is your highest category` : 'Start logging to see patterns'}</Text><Text style={s.insightBody}>{comparison} {budget ? `${remaining >= 0 ? pesos(remaining) + ' remains' : pesos(-remaining) + ' over'} in your monthly budget.` : 'Set a monthly budget for remaining-budget insights.'}</Text></View></View></>}
    <TransactionForm visible={transactionOpen} wallets={store.wallets} onClose={() => setTransactionOpen(false)} onSave={store.addTransaction} /><WalletForm visible={walletOpen} onClose={() => setWalletOpen(false)} onSave={store.addWallet} />
  </ScrollView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream }, iconButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' }, hero: { borderRadius: 23, padding: 21 }, heroLabel: { color: '#C7DCCE', fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, heroAmount: { color: 'white', fontSize: 36, fontWeight: '800', marginTop: 7, letterSpacing: -1 }, heroStats: { flexDirection: 'row', gap: 38, marginTop: 22 }, heroMiniLabel: { color: '#B8CFC1', fontSize: 9, fontWeight: '800', marginBottom: 4 }, income: { color: colors.lime, fontWeight: '800' }, expense: { color: '#FFD9C5', fontWeight: '800' }, add: { height: 55, backgroundColor: colors.ink, borderRadius: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 14 }, addText: { color: 'white', fontWeight: '800' }, grid: { flexDirection: 'row', gap: 10, marginTop: 16 }, metric: { flex: 1, minHeight: 104, padding: 14, borderRadius: 18, backgroundColor: 'white' }, metricLabel: { fontSize: 9, color: colors.muted, fontWeight: '800', letterSpacing: .8 }, metricValue: { fontSize: 17, color: colors.ink, fontWeight: '800', marginTop: 9 }, metricSub: { fontSize: 10, color: colors.muted, marginTop: 4 }, heading: { fontSize: 18, fontWeight: '800', color: colors.ink, marginTop: 26, marginBottom: 9 }, card: { backgroundColor: 'white', borderRadius: 19, paddingHorizontal: 15, paddingVertical: 3 }, breakdown: { paddingVertical: 10 }, breakdownLabel: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 7 }, breakdownName: { color: colors.ink, fontWeight: '700', fontSize: 13 }, breakdownValue: { color: colors.ink, fontWeight: '800', fontSize: 12 }, track: { height: 7, borderRadius: 4, backgroundColor: colors.line, overflow: 'hidden' }, fill: { height: 7, backgroundColor: colors.green, borderRadius: 4 }, noData: { padding: 20, textAlign: 'center', color: colors.muted }, insight: { flexDirection: 'row', gap: 11, padding: 16, backgroundColor: colors.mint, borderRadius: 19 }, insightTitle: { color: colors.green, fontWeight: '800', marginBottom: 5 }, insightBody: { color: '#466151', fontSize: 12, lineHeight: 18 } });
