import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { EmptyState, ErrorState, LoadingState, ScreenHeader } from '@/components';
import { TransferForm, WalletForm } from '@/forms';
import { pesos } from '@/money';
import { useStore } from '@/store';
import { colors } from '@/theme';
import { Wallet } from '@/types';

export default function Wallets() {
  const { top } = useSafeAreaInsets(); const store = useStore(); const [walletOpen, setWalletOpen] = useState(false); const [transferOpen, setTransferOpen] = useState(false); const [editing, setEditing] = useState<Wallet | null>(null);
  function remove(wallet: Wallet) { Alert.alert(`Delete ${wallet.name}?`, 'Wallets with linked transactions or transfers cannot be deleted.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await store.removeWallet(wallet.id); } catch (error: any) { Alert.alert('Cannot delete wallet', error?.message || 'This wallet has linked records.'); } } }]); }
  return <ScrollView style={s.page} contentContainerStyle={{ paddingTop: top + 16, paddingHorizontal: 18, paddingBottom: 30 }}><ScreenHeader eyebrow="Where your money lives" title="Wallets" action={<Pressable style={s.add} onPress={() => { setEditing(null); setWalletOpen(true); }}><Ionicons name="add" size={22} color="white" /></Pressable>} />{store.error ? <ErrorState message={store.error} /> : !store.loaded ? <LoadingState /> : <>{store.wallets.length ? store.wallets.map((wallet, index) => <View key={wallet.id} style={[s.wallet, { backgroundColor: index % 2 ? '#E4F4EC' : colors.green }]}><View style={s.walletTop}><View style={[s.walletIcon, index % 2 ? { backgroundColor: 'white' } : {}]}><Ionicons name={wallet.name.toLowerCase().includes('cash') ? 'cash-outline' : wallet.name.toLowerCase().includes('bank') ? 'business-outline' : 'wallet-outline'} size={22} color={index % 2 ? colors.green : 'white'} /></View><View style={s.walletActions}><Pressable onPress={() => { setEditing(wallet); setWalletOpen(true); }}><Ionicons name="pencil-outline" size={19} color={index % 2 ? colors.green : 'white'} /></Pressable><Pressable onPress={() => remove(wallet)}><Ionicons name="trash-outline" size={19} color={index % 2 ? colors.red : '#FFD6D1'} /></Pressable></View></View><Text style={[s.walletName, index % 2 === 1 && { color: colors.green }]}>{wallet.name}</Text><Text style={[s.balance, index % 2 === 1 && { color: colors.ink }]}>{pesos(store.walletBalance(wallet.id))}</Text><Text style={[s.opening, index % 2 === 1 && { color: colors.muted }]}>Opening balance {pesos(wallet.openingBalanceCents)}</Text></View>) : <EmptyState icon="wallet-outline" title="Create your first wallet" body="Add Cash, GCash, a bank account, or any place you keep money." />}
    <Pressable disabled={store.wallets.length < 2} onPress={() => setTransferOpen(true)} style={[s.transferButton, store.wallets.length < 2 && { opacity: .45 }]}><Ionicons name="swap-horizontal" size={21} color="white" /><Text style={s.transferText}>Transfer between wallets</Text></Pressable>
    <Text style={s.heading}>Recent transfers</Text>{store.transfers.length ? <View style={s.list}>{store.transfers.slice(0, 10).map((item) => <View key={item.id} style={s.transferRow}><View style={s.swap}><Ionicons name="swap-horizontal" size={18} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={s.transferTitle}>{store.wallets.find((w) => w.id === item.fromWalletId)?.name || 'Wallet'} → {store.wallets.find((w) => w.id === item.toWalletId)?.name || 'Wallet'}</Text><Text style={s.transferMeta}>{item.transferDate} · {item.description}</Text></View><Text style={s.transferAmount}>{pesos(item.amountCents)}</Text></View>)}</View> : <Text style={s.emptyTransfers}>No transfers yet. Transfers move money without counting as income or expenses.</Text>}</>}
    <WalletForm visible={walletOpen} initial={editing} onClose={() => setWalletOpen(false)} onSave={(value) => editing ? store.updateWallet(editing.id, value) : store.addWallet(value)} /><TransferForm visible={transferOpen} wallets={store.wallets} onClose={() => setTransferOpen(false)} onSave={store.addTransfer} />
  </ScrollView>;
}
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream }, add: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' }, wallet: { padding: 18, borderRadius: 21, marginBottom: 11 }, walletTop: { flexDirection: 'row', justifyContent: 'space-between' }, walletIcon: { width: 40, height: 40, borderRadius: 13, backgroundColor: '#FFFFFF24', alignItems: 'center', justifyContent: 'center' }, walletActions: { flexDirection: 'row', gap: 18, paddingTop: 8 }, walletName: { color: '#C9E1D1', fontWeight: '700', fontSize: 13, marginTop: 15 }, balance: { color: 'white', fontSize: 27, fontWeight: '800', marginTop: 4 }, opening: { color: '#B7D0C0', fontSize: 10, marginTop: 5 }, transferButton: { height: 54, borderRadius: 17, backgroundColor: colors.ink, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 5 }, transferText: { color: 'white', fontWeight: '800' }, heading: { fontSize: 18, color: colors.ink, fontWeight: '800', marginTop: 27, marginBottom: 9 }, list: { backgroundColor: 'white', borderRadius: 19, paddingHorizontal: 14 }, transferRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: colors.line }, swap: { width: 37, height: 37, borderRadius: 12, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' }, transferTitle: { color: colors.ink, fontWeight: '700', fontSize: 13 }, transferMeta: { color: colors.muted, fontSize: 10, marginTop: 3 }, transferAmount: { color: colors.ink, fontWeight: '800', fontSize: 12 }, emptyTransfers: { color: colors.muted, textAlign: 'center', backgroundColor: 'white', borderRadius: 17, padding: 20, fontSize: 12, lineHeight: 18 } });
