import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { fromCents, manilaToday, toCents, validDate } from './money';
import { colors } from './theme';
import { EXPENSE_CATEGORIES, INCOME_CATEGORIES, Transaction, TransactionInput, TransactionType, TransferInput, Wallet, WalletInput } from './types';

function Shell({ visible, title, children, onClose }: { visible: boolean; title: string; children: React.ReactNode; onClose: () => void }) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><KeyboardAvoidingView style={s.overlay} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Pressable style={{ flex: 1 }} onPress={onClose} /><View style={s.sheet}><View style={s.handle} /><View style={s.heading}><Text style={s.title}>{title}</Text><Pressable onPress={onClose} hitSlop={12}><Ionicons name="close" size={24} color={colors.ink} /></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>{children}</ScrollView></View></KeyboardAvoidingView></Modal>; }
function Label({ children }: { children: React.ReactNode }) { return <Text style={s.label}>{children}</Text>; }
function Chips({ values, selected, onChange }: { values: readonly string[]; selected: string; onChange: (value: any) => void }) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{values.map((value) => <Pressable key={value} onPress={() => onChange(value)} style={[s.chip, selected === value && s.chipOn]}><Text style={[s.chipText, selected === value && { color: 'white' }]}>{value}</Text></Pressable>)}</ScrollView>; }

export function TransactionForm({ visible, wallets, initial, onClose, onSave }: { visible: boolean; wallets: Wallet[]; initial?: Transaction | null; onClose: () => void; onSave: (value: TransactionInput) => Promise<void> }) {
  const [type, setType] = useState<TransactionType>('expense'); const [amount, setAmount] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState<string>('Food'); const [walletId, setWalletId] = useState(''); const [date, setDate] = useState(manilaToday()); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!visible) return; setType(initial?.type || 'expense'); setAmount(initial ? fromCents(initial.amountCents) : ''); setDescription(initial?.description || ''); setCategory(initial?.category || 'Food'); setWalletId(initial?.walletId || wallets[0]?.id || ''); setDate(initial?.transactionDate || manilaToday()); setError(''); }, [visible, initial, wallets]);
  useEffect(() => { const allowed = type === 'expense' ? EXPENSE_CATEGORIES : INCOME_CATEGORIES; if (!allowed.includes(category as any)) setCategory(allowed[0]); }, [type]);
  async function submit() { const amountCents = toCents(amount); if (amountCents <= 0 || !description.trim() || !walletId || !validDate(date)) { setError('Enter a positive amount, description, wallet, and valid YYYY-MM-DD date.'); return; } setSaving(true); setError(''); try { await onSave({ amountCents, type, description: description.trim(), category: category as any, walletId, transactionDate: date }); onClose(); } catch { setError('Could not save. Check your connection and try again.'); } finally { setSaving(false); } }
  return <Shell visible={visible} title={initial ? 'Edit transaction' : 'Add transaction'} onClose={onClose}><Label>TYPE</Label><View style={s.segment}><Pressable onPress={() => setType('expense')} style={[s.segmentItem, type === 'expense' && s.segmentOn]}><Text style={[s.segmentText, type === 'expense' && s.segmentTextOn]}>Expense</Text></Pressable><Pressable onPress={() => setType('income')} style={[s.segmentItem, type === 'income' && s.segmentOn]}><Text style={[s.segmentText, type === 'income' && s.segmentTextOn]}>Income</Text></Pressable></View><Label>AMOUNT</Label><View style={s.amount}><Text style={s.peso}>₱</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0.00" style={s.amountInput} /></View><Label>DESCRIPTION</Label><TextInput value={description} onChangeText={setDescription} placeholder="What was this for?" style={s.input} /><Label>CATEGORY</Label><Chips values={type === 'expense' ? EXPENSE_CATEGORIES : INCOME_CATEGORIES} selected={category} onChange={setCategory} /><Label>WALLET</Label><Chips values={wallets.map((item) => item.name)} selected={wallets.find((item) => item.id === walletId)?.name || ''} onChange={(name) => setWalletId(wallets.find((item) => item.name === name)?.id || '')} /><Label>DATE (YYYY-MM-DD)</Label><TextInput value={date} onChangeText={setDate} placeholder="2026-10-05" style={s.input} />{!!error && <Text style={s.error}>{error}</Text>}<Pressable disabled={saving} onPress={submit} style={[s.save, saving && { opacity: .5 }]}><Text style={s.saveText}>{saving ? 'Saving…' : 'Save transaction'}</Text></Pressable></Shell>;
}

export function WalletForm({ visible, initial, onClose, onSave }: { visible: boolean; initial?: Wallet | null; onClose: () => void; onSave: (value: WalletInput) => Promise<void> }) { const [name, setName] = useState(''); const [balance, setBalance] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); useEffect(() => { if (visible) { setName(initial?.name || ''); setBalance(initial ? fromCents(initial.openingBalanceCents) : ''); setError(''); } }, [visible, initial]); async function submit() { if (!name.trim() || !balance.trim() || toCents(balance) < 0) { setError('Enter a wallet name and a non-negative opening balance.'); return; } setSaving(true); try { await onSave({ name: name.trim(), openingBalanceCents: toCents(balance) }); onClose(); } catch { setError('Could not save this wallet.'); } finally { setSaving(false); } } return <Shell visible={visible} title={initial ? 'Edit wallet' : 'New wallet'} onClose={onClose}><Label>WALLET NAME</Label><TextInput value={name} onChangeText={setName} placeholder="Cash, GCash, Bank…" style={s.input} /><Label>OPENING BALANCE</Label><View style={s.amount}><Text style={s.peso}>₱</Text><TextInput value={balance} onChangeText={setBalance} keyboardType="decimal-pad" placeholder="0.00" style={s.amountInput} /></View><Text style={s.help}>This is the amount already in the wallet before your first recorded transaction.</Text>{!!error && <Text style={s.error}>{error}</Text>}<Pressable disabled={saving} onPress={submit} style={s.save}><Text style={s.saveText}>{saving ? 'Saving…' : 'Save wallet'}</Text></Pressable></Shell>; }

export function TransferForm({ visible, wallets, onClose, onSave }: { visible: boolean; wallets: Wallet[]; onClose: () => void; onSave: (value: TransferInput) => Promise<void> }) { const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [amount, setAmount] = useState(''); const [description, setDescription] = useState('Wallet transfer'); const [date, setDate] = useState(manilaToday()); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); useEffect(() => { if (visible) { setFrom(wallets[0]?.id || ''); setTo(wallets[1]?.id || ''); setAmount(''); setDate(manilaToday()); setError(''); } }, [visible, wallets]); async function submit() { const cents = toCents(amount); if (cents <= 0 || !from || !to || from === to || !validDate(date)) { setError('Choose two different wallets, a positive amount, and a valid date.'); return; } setSaving(true); try { await onSave({ fromWalletId: from, toWalletId: to, amountCents: cents, description: description.trim() || 'Wallet transfer', transferDate: date }); onClose(); } catch { setError('Could not save this transfer.'); } finally { setSaving(false); } } const selector = (label: string, selected: string, onChange: (id: string) => void) => <><Label>{label}</Label><Chips values={wallets.map((item) => item.name)} selected={wallets.find((item) => item.id === selected)?.name || ''} onChange={(name) => onChange(wallets.find((item) => item.name === name)?.id || '')} /></>; return <Shell visible={visible} title="Transfer money" onClose={onClose}>{selector('FROM', from, setFrom)}{selector('TO', to, setTo)}<Label>AMOUNT</Label><View style={s.amount}><Text style={s.peso}>₱</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0.00" style={s.amountInput} /></View><Label>DESCRIPTION</Label><TextInput value={description} onChangeText={setDescription} style={s.input} /><Label>DATE (YYYY-MM-DD)</Label><TextInput value={date} onChangeText={setDate} style={s.input} />{!!error && <Text style={s.error}>{error}</Text>}<Pressable disabled={saving} onPress={submit} style={s.save}><Text style={s.saveText}>{saving ? 'Transferring…' : 'Transfer money'}</Text></Pressable></Shell>; }

const s = StyleSheet.create({ overlay: { flex: 1, backgroundColor: '#0B160F66', justifyContent: 'flex-end' }, sheet: { maxHeight: '90%', backgroundColor: colors.cream, padding: 20, paddingBottom: 32, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, handle: { width: 44, height: 5, borderRadius: 3, backgroundColor: '#CBD0CC', alignSelf: 'center', marginBottom: 16 }, heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, title: { fontSize: 25, fontWeight: '800', color: colors.ink }, label: { color: colors.muted, fontWeight: '800', fontSize: 10, letterSpacing: 1, marginTop: 14, marginBottom: 7 }, input: { backgroundColor: 'white', minHeight: 50, borderRadius: 14, paddingHorizontal: 14, color: colors.ink, borderWidth: 1, borderColor: colors.line }, segment: { flexDirection: 'row', backgroundColor: '#E8EAE6', padding: 3, borderRadius: 14 }, segmentItem: { flex: 1, height: 41, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, segmentOn: { backgroundColor: colors.green }, segmentText: { fontWeight: '700', color: colors.muted }, segmentTextOn: { color: 'white' }, amount: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderColor: '#C8CEC9' }, peso: { fontSize: 30, fontWeight: '700', color: colors.muted }, amountInput: { flex: 1, fontSize: 36, fontWeight: '800', color: colors.ink, padding: 8 }, chips: { gap: 7, paddingRight: 15 }, chip: { height: 38, justifyContent: 'center', paddingHorizontal: 13, borderRadius: 13, backgroundColor: 'white', borderWidth: 1, borderColor: colors.line }, chipOn: { backgroundColor: colors.green, borderColor: colors.green }, chipText: { color: colors.ink, fontWeight: '700', fontSize: 12 }, error: { color: colors.red, fontSize: 12, lineHeight: 17, marginTop: 12 }, help: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 8 }, save: { height: 54, borderRadius: 17, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', marginTop: 22, marginBottom: 6 }, saveText: { color: 'white', fontSize: 15, fontWeight: '800' } });
